/*
+-------------------------------------------------------------------------+
|      This file was generated by The Interactive Disassembler (IDA)      |
|                         and rewriten by bang1338                        |
|           Copyright (c) 2022 Hex-Rays, <support@hex-rays.com>           |
|           Copyright (c) 2022 bang1338, <bangk1338@gmail.com>            |
+-------------------------------------------------------------------------+

Input SHA256 : 4B57103C56ED307DA3D78E96FC9DA3C42F54E82865A4375F77850BAD4B2DD4F9
Input SHA1   : 2EF23759BBC71E480BBF9497F98677AD82A3CF43
Input MD5    : 71DFCF127556A4F5F8B78EC5BE707743
Input CRC32  : EE0E476B

File Name   : fun code run it.exe
By          : mintttt131v2/Nguyen Luong Hieu
Type:       : Trollware
Format      : Portable executable for 80386 (PE)
Imagebase   : 400000
Timestamp   : 1E09C522 (Fri Dec 20 19:59:30 1985)
Section 1. (virtual address 00001000)
Virtual size                  : 000B6C90 ( 748688.)
Section size in file          : 000B6E00 ( 749056.)
Offset to raw data for section: 00000400
Flags 60500060: Text Data Executable Readable
Alignment     : 16 bytes
OS type         :  MS Windows
Application type:  Executable 32bit
Detected compiler: GNU C++
Tools:           : IDA Pro 7.7.220118, Hex-Rays Decompiler 7.5.0.200728, 
                   Notepad++ 8.4.4, Shadow Defender 1.5.0.726, Code::Block 20.03
*/

#include <iostream>
#include <windows.h>
using namespace std;

int main()
{
    int n; // Get value of n
    int i; // Time of running url

    cout << "You want to play the game?[yes = 1, no = 0]";    // Ask the user
    cin >> n;
    n = 1;                                   // Whatever it is, the input still 1 (mean yes, begin the troll)
    cout << "Glad you said yes";             // You know :)
    for ( i = 0; i <= 14; i++ )              // Run URL 0-14 times
        ShellExecute(NULL, "open", "https://www.youtube.com/watch?v=oHg5SJYRHA0", NULL, NULL, SW_SHOWNORMAL);  // Open the URL
    return 0;
}
